[failure] Type error!
fail
          Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
          Called from Alcotest_engine__Core.Make.protect_test.(fun) in file "src/alcotest-engine/core.ml", line 180, characters 17-23
          Called from Alcotest_engine__Monad.Identity.catch in file "src/alcotest-engine/monad.ml", line 24, characters 31-35
          